version: "3"

services:
  main:
    build: ./serverMain
    ports:
      - "3030:3030"
    environment:
      PORT: "3030"
      DB_SERVICE_PORT: "3031"
      DB_SERVICE_NAME: "serverdb"
    networks:
      - general

  serverdb:
    build: ./serverDB
    ports:
      - "3031:3031"
    environment:
      PORT: "3031"
      DB_PORT: "27017"
      DB_NAME: "mongo"
    networks:
      - general
  
  serverpy:
    build: ./serverPy
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "hello.py"
    networks: 
     - general
  
  mongo:
    image: mongo:latest
    networks:
      - general

networks:
  general: